name: CI

on:
  - push
  - pull_request

jobs:
  pipeline:
    name: pipiline(${{ matrix.module.name }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module:
          - name: codegen
            directory: ./_codegen
          - name: fun
            directory: .
    defaults:
      run:
        working-directory: ${{ matrix.module.directory }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: 1.14
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28
      - name: Build
        run: make install
      - name: Test
        run: make test
      - uses: codecov/codecov-action@v1